import time

code = input("PS C:/Users/Your-pc> ")
if code == "$bash":
    print("Bashing 10%")
    time.sleep(.1)
    print("Bashing 20%")
    time.sleep(.1)
    print("Bashing 20%")
    time.sleep(.1)
    print("Bashing 30%")
    time.sleep(.1)
    print("Bashing 40%")
    time.sleep(.1)
    print("Bashing 50%")
    time.sleep(.1)
    print("Bashing 60%")
    time.sleep(.1)
    print("Bashing 70%")
    time.sleep(2)
    print("Bashing 80%")
    time.sleep(.1)
    print("Bashing 90%")
    time.sleep(.1)
    print("Bashing 100%")
    time.sleep(1)
    print("Bashing Completed!")
elif code == "$format":
    print("Formatting 10%")
    time.sleep(.1)
    print("Formatting 20%")
    time.sleep(.1)
    print("Formatting 20%")
    time.sleep(.1)
    print("Formatting 30%")
    time.sleep(.1)
    print("Formatting 40%")
    time.sleep(.1)
    print("Formatting 50%")
    time.sleep(.1)
    print("Formatting 60%")
    time.sleep(.1)
    print("Formatting 70%")
    time.sleep(.1)
    print("Formatting 80%")
    time.sleep(.1)
    print("Formatting 90%")
    time.sleep(2)
    print("formatting 100%")
    time.sleep(1)
    print("Formatting Completed!")
else:
    print("PS C:/Users/Your-pc> Unknown Command")
